// This file is generated by Slice Machine. Update with care!

import Evenement from './Evenement';
import Prix from './Prix';
import TextBlock from './TextBlock';

export {
	Evenement,
	Prix,
	TextBlock,
};

export const components = {
	event: Evenement,
	price: Prix,
	text_block: TextBlock,
};
